import HorizontalHeader from "@/src/components/HorizontalHeader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-grid-layout/css/styles.css";
import "react-resizable/css/styles.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mb-auto">{children}</main>

        <HorizontalHeader />
      </body>
    </html>
  );
}
